<?php

namespace Database\Seeders;

use App\Models\Banco\Banco;
use Illuminate\Database\Seeder;

class BancoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //no pais_id nesse instante coloca 1 para todos os paises por favor

        //crie uma linha dessa para cada banco que quiser efetuar ot cadastro prévio =)
        //Banco::create(['nome' => 'nome do banco', 'codigo' => 'codigo febraban', 'pais_id' => 1]);
        Banco::create(['nome' =>'Banco Do Brasil S.A ','codigo' => '001','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Da Amazônia S.A.','codigo' => '003','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Do Nordeste Do Brasil S.A.','codigo' => '004','pais_id' => 1]);
        Banco::create(['nome' =>'Bndes (Banco Nacional Do Desenvolvimento Social)','codigo' => '007','pais_id' => 1]);
        Banco::create(['nome' =>'Credicoamo Crédito Rural Cooperativa','codigo' => '010','pais_id' => 1]);
        Banco::create(['nome' =>'C.Suisse Hedging-Griffo Cv S.A (Credit Suisse)','codigo' => '011','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Inbursa','codigo' => '012','pais_id' => 1]);
        Banco::create(['nome' =>'Natixis Brasil S.A.','codigo' => '014','pais_id' => 1]);
        Banco::create(['nome' =>'Ubs Brasil Cctvm S.A.','codigo' => '015','pais_id' => 1]);
        Banco::create(['nome' =>'Cooperativa De Crédito Mútuo Dos Despachantes De Trânsito De Santa Catarina E Ri','codigo' => '016','pais_id' => 1]);
        Banco::create(['nome' =>'Bny Mellon Banco S.A.','codigo' => '017','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Tricury S.A.','codigo' => '018','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Banestes S.A.','codigo' => '021','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Bandepe S.A.','codigo' => '024','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Alfa S.A.','codigo' => '025','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Itaú Consignado S.A.','codigo' => '029','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Santander Brasil S.A.','codigo' => '033','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Bradesco Bbi S.A.','codigo' => '036','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Do Estado Do Pará S.A.','codigo' => '037','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Cargill S.A.','codigo' => '040','pais_id' => 1]);
        Banco::create(['nome' =>'Banrisul – Banco Do Estado Do Rio Grande Do Sul S.A.','codigo' => '041','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Do Estado De Sergipe S.A.','codigo' => '047','pais_id' => 1]);
        Banco::create(['nome' =>'Confidence Cc S.A.','codigo' => '060','pais_id' => 1]);
        Banco::create(['nome' =>'Hipercard Banco Múltiplo S.A.','codigo' => '062','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Bradescard','codigo' => '063','pais_id' => 1]);
        Banco::create(['nome' =>'Goldman Sachs Do Brasil Bm S.A.','codigo' => '064','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Andbank S.A.','codigo' => '065','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Morgan Stanley S.A.','codigo' => '066','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Crefisa S.A.','codigo' => '069','pais_id' => 1]);
        Banco::create(['nome' =>'Brb – Banco De Brasília S.A.','codigo' => '070','pais_id' => 1]);
        Banco::create(['nome' =>'Banco J. Safra S.A.','codigo' => '074','pais_id' => 1]);
        Banco::create(['nome' =>'Bco Abn Amro S.A.','codigo' => '075','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Kdb Brasil S.A.','codigo' => '076','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Inter S.A.','codigo' => '077','pais_id' => 1]);
        Banco::create(['nome' =>'Haitong Bi Do Brasil S.A.','codigo' => '078','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Original Do Agronegócio S.A.','codigo' => '079','pais_id' => 1]);
        Banco::create(['nome' =>'B&T Cc Ltda','codigo' => '080','pais_id' => 1]);
        Banco::create(['nome' =>'Bbn Banco Brasileiro De Negocios S.A.','codigo' => '081','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Topázio S.A.','codigo' => '082','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Da China Brasil S.A.','codigo' => '083','pais_id' => 1]);
        Banco::create(['nome' =>'Uniprime Norte Do Paraná – Cooperativa De Crédito Ltda','codigo' => '084','pais_id' => 1]);
        Banco::create(['nome' =>'Cooperativa Central De Créditos – Ailos','codigo' => '085','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Randon S.A.','codigo' => '088','pais_id' => 1]);
        Banco::create(['nome' =>'Credisan Cooperativa De Crédito','codigo' => '089','pais_id' => 1]);
        Banco::create(['nome' =>'Central De Cooperativas De Economia E Crédito Mútuo Do Estado Do Rio Grande Do S','codigo' => '091','pais_id' => 1]);
        Banco::create(['nome' =>'Brk S.A.','codigo' => '092','pais_id' => 1]);
        Banco::create(['nome' =>'Pólocred Scmepp Ltda','codigo' => '093','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Finaxis','codigo' => '094','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Confidence De Câmbio S.A.','codigo' => '095','pais_id' => 1]);
        Banco::create(['nome' =>'Banco B3 S.A.','codigo' => '096','pais_id' => 1]);
        Banco::create(['nome' =>'Credisis – Central De Cooperativas De Crédito Ltda.','codigo' => '097','pais_id' => 1]);
        Banco::create(['nome' =>'Credialiança Ccr','codigo' => '098','pais_id' => 1]);
        Banco::create(['nome' =>'Uniprime Central Ccc Ltda','codigo' => '099','pais_id' => 1]);
        Banco::create(['nome' =>'Planner Corretora De Valores S.A.','codigo' => '100','pais_id' => 1]);
        Banco::create(['nome' =>'Renascença Dtvm Ltda','codigo' => '101','pais_id' => 1]);
        Banco::create(['nome' =>'Xp Investimentos S.A.','codigo' => '102','pais_id' => 1]);
        Banco::create(['nome' =>'Caixa Econômica Federal (Cef)','codigo' => '104','pais_id' => 1]);
        Banco::create(['nome' =>'Lecca Cfi S.A.','codigo' => '105','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Bocom Bbm S.A.','codigo' => '107','pais_id' => 1]);
        Banco::create(['nome' =>'Portocred S.A.','codigo' => '108','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Oliveira Trust Dtvm S.A.','codigo' => '111','pais_id' => 1]);
        Banco::create(['nome' =>'Magliano S.A.','codigo' => '113','pais_id' => 1]);
        Banco::create(['nome' =>'Central Cooperativa De Crédito No Estado Do Espírito Santo','codigo' => '114','pais_id' => 1]);
        Banco::create(['nome' =>'Advanced Cc Ltda','codigo' => '117','pais_id' => 1]);
        Banco::create(['nome' =>'Standard Chartered Bi S.A.','codigo' => '118','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Western Union Do Brasil S.A.','codigo' => '119','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Rodobens S.A.','codigo' => '120','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Agibank S.A.','codigo' => '121','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Bradesco Berj S.A.','codigo' => '122','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Woori Bank Do Brasil S.A.','codigo' => '124','pais_id' => 1]);
        Banco::create(['nome' =>'Brasil Plural S.A Banco','codigo' => '125','pais_id' => 1]);
        Banco::create(['nome' =>'Br Partners Banco De Investimento S.A.','codigo' => '126','pais_id' => 1]);
        Banco::create(['nome' =>'Codepe Cvc S.A.','codigo' => '127','pais_id' => 1]);
        Banco::create(['nome' =>'Ms Bank S.A Banco De Câmbio','codigo' => '128','pais_id' => 1]);
        Banco::create(['nome' =>'Ubs Brasil Bi S.A.','codigo' => '129','pais_id' => 1]);
        Banco::create(['nome' =>'Caruana Scfi','codigo' => '130','pais_id' => 1]);
        Banco::create(['nome' =>'Tullett Prebon Brasil Cvc Ltda','codigo' => '131','pais_id' => 1]);
        Banco::create(['nome' =>'Icbc Do Brasil Bm S.A.','codigo' => '132','pais_id' => 1]);
        Banco::create(['nome' =>'Cresol Confederação','codigo' => '133','pais_id' => 1]);
        Banco::create(['nome' =>'Bgc Liquidez Dtvm Ltda','codigo' => '134','pais_id' => 1]);
        Banco::create(['nome' =>'Unicred Cooperativa Ltda','codigo' => '136','pais_id' => 1]);
        Banco::create(['nome' =>'Multimoney Cc Ltda','codigo' => '137','pais_id' => 1]);
        Banco::create(['nome' =>'Get Money Cc Ltda','codigo' => '138','pais_id' => 1]);
        Banco::create(['nome' =>'Intesa Sanpaolo Brasil S.A.','codigo' => '139','pais_id' => 1]);
        Banco::create(['nome' =>'Easynvest – Título Cv S.A.','codigo' => '140','pais_id' => 1]);
        Banco::create(['nome' =>'Broker Brasil Cc Ltda','codigo' => '142','pais_id' => 1]);
        Banco::create(['nome' =>'Treviso Cc S.A.','codigo' => '143','pais_id' => 1]);
        Banco::create(['nome' =>'Bexs Banco De Cambio S.A.','codigo' => '144','pais_id' => 1]);
        Banco::create(['nome' =>'Levycam Ccv Ltda','codigo' => '145','pais_id' => 1]);
        Banco::create(['nome' =>'Guitta Cc Ltda','codigo' => '146','pais_id' => 1]);
        Banco::create(['nome' =>'Facta S.A. Cfi','codigo' => '149','pais_id' => 1]);
        Banco::create(['nome' =>'Icap Do Brasil Ctvm Ltda','codigo' => '157','pais_id' => 1]);
        Banco::create(['nome' =>'Casa Do Crédito S.A.','codigo' => '159','pais_id' => 1]);
        Banco::create(['nome' =>'Commerzbank Brasil S.A Banco Múltiplo','codigo' => '163','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Olé Bonsucesso Consignado S.A.','codigo' => '169','pais_id' => 1]);
        Banco::create(['nome' =>'Albatross Ccv S.A.','codigo' => '172','pais_id' => 1]);
        Banco::create(['nome' =>'Brl Trust Dtvm Sa','codigo' => '173','pais_id' => 1]);
        Banco::create(['nome' =>'Pefisa S.A. – Crédito, Financiamento E Investimento','codigo' => '174','pais_id' => 1]);
        Banco::create(['nome' =>'Guide Investimentos S.A. Corretora De Valores','codigo' => '177','pais_id' => 1]);
        Banco::create(['nome' =>'Cm Capital Markets Cctvm Ltda','codigo' => '180','pais_id' => 1]);
        Banco::create(['nome' =>'Dacasa Financeira S/A','codigo' => '182','pais_id' => 1]);
        Banco::create(['nome' =>'Socred S.A.','codigo' => '183','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Itaú Bba S.A.','codigo' => '184','pais_id' => 1]);
        Banco::create(['nome' =>'Ativa S.A Investimentos','codigo' => '188','pais_id' => 1]);
        Banco::create(['nome' =>'Hs Financeira','codigo' => '189','pais_id' => 1]);
        Banco::create(['nome' =>'Servicoop','codigo' => '190','pais_id' => 1]);
        Banco::create(['nome' =>'Nova Futura Ctvm Ltda','codigo' => '191','pais_id' => 1]);
        Banco::create(['nome' =>'Parmetal Dtvm Ltda','codigo' => '194','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Fair Cc S.A.','codigo' => '196','pais_id' => 1]);
        Banco::create(['nome' =>'Stone Pagamentos S.A.','codigo' => '197','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Bradesco Cartoes S.A.','codigo' => '204','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Btg Pactual S.A.','codigo' => '208','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Original S.A.','codigo' => '212','pais_id' => 1]);
        Banco::create(['nome' =>'Bco Arbi S.A.','codigo' => '213','pais_id' => 1]);
        Banco::create(['nome' =>'Banco John Deere S.A.','codigo' => '217','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Bs2 S.A.','codigo' => '218','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Crédit Agricole Br S.A.','codigo' => '222','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Fibra S.A.','codigo' => '224','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Cifra S.A.','codigo' => '233','pais_id' => 1]);
        Banco::create(['nome' =>'Bradesco S.A.','codigo' => '237','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Classico S.A.','codigo' => '241','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Máxima S.A.','codigo' => '243','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Abc Brasil S.A.','codigo' => '246','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Investcred Unibanco S.A.','codigo' => '249','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Bcv','codigo' => '250','pais_id' => 1]);
        Banco::create(['nome' =>'Bexs Cc S.A.','codigo' => '253','pais_id' => 1]);
        Banco::create(['nome' =>'Paraná Banco S.A.','codigo' => '254','pais_id' => 1]);
        Banco::create(['nome' =>'Moneycorp Banco De Câmbio S.A.','codigo' => '259','pais_id' => 1]);
        Banco::create(['nome' =>'Nu Pagamentos S.A (Nubank)','codigo' => '260','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Fator S.A.','codigo' => '265','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Cedula S.A.','codigo' => '266','pais_id' => 1]);
        Banco::create(['nome' =>'Barigui Companhia Hipotecária','codigo' => '268','pais_id' => 1]);
        Banco::create(['nome' =>'Hsbc Banco De Investimento','codigo' => '269','pais_id' => 1]);
        Banco::create(['nome' =>'Sagitur Cc Ltda','codigo' => '270','pais_id' => 1]);
        Banco::create(['nome' =>'Ib Cctvm Ltda','codigo' => '271','pais_id' => 1]);
        Banco::create(['nome' =>'Agk Corretora De Câmbio S.A.','codigo' => '272','pais_id' => 1]);
        Banco::create(['nome' =>'Ccr De São Miguel Do Oeste','codigo' => '273','pais_id' => 1]);
        Banco::create(['nome' =>'Money Plus Sociedade De Crédito Ao Microempreendedor E A Empresa De Pequeno Port','codigo' => '274','pais_id' => 1]);
        Banco::create(['nome' =>'Senff S.A.','codigo' => '276','pais_id' => 1]);
        Banco::create(['nome' =>'Genial Investimentos Cvm S.A.','codigo' => '278','pais_id' => 1]);
        Banco::create(['nome' =>'Ccr De Primavera Do Leste','codigo' => '279','pais_id' => 1]);
        Banco::create(['nome' =>'Avista S.A.','codigo' => '280','pais_id' => 1]);
        Banco::create(['nome' =>'Cooperativa De Crédito Rural Coopavel','codigo' => '281','pais_id' => 1]);
        Banco::create(['nome' =>'Rb Capital Investimentos Dtvm Ltda','codigo' => '283','pais_id' => 1]);
        Banco::create(['nome' =>'Frente Cc Ltda','codigo' => '285','pais_id' => 1]);
        Banco::create(['nome' =>'Cooperativa De Crédito Rural De De Ouro','codigo' => '286','pais_id' => 1]);
        Banco::create(['nome' =>'Carol Dtvm Ltda','codigo' => '288','pais_id' => 1]);
        Banco::create(['nome' =>'Decyseo Corretora De Cambio Ltda.','codigo' => '289','pais_id' => 1]);
        Banco::create(['nome' =>'Pagseguro Internet S.A.','codigo' => '290','pais_id' => 1]);
        Banco::create(['nome' =>'Bs2 Distribuidora De Títulos E Investimentos','codigo' => '292','pais_id' => 1]);
        Banco::create(['nome' =>'Lastro Rdv Dtvm Ltda','codigo' => '293','pais_id' => 1]);
        Banco::create(['nome' =>'Vision S.A. Corretora De Cambio','codigo' => '296','pais_id' => 1]);
        Banco::create(['nome' =>'Vip’S Cc Ltda','codigo' => '298','pais_id' => 1]);
        Banco::create(['nome' =>'Sorocred   Crédito, Financiamento E Investimento S.A.','codigo' => '299','pais_id' => 1]);
        Banco::create(['nome' =>'Banco La Nacion Argentina','codigo' => '300','pais_id' => 1]);
        Banco::create(['nome' =>'Bpp Instituição De Pagamentos S.A.','codigo' => '301','pais_id' => 1]);
        Banco::create(['nome' =>'Portopar Distribuidora De Titulos E Valores Mobiliarios Ltda.','codigo' => '306','pais_id' => 1]);
        Banco::create(['nome' =>'Terra Investimentos Distribuidora De Títulos E Valores Mobiliários Ltda.','codigo' => '307','pais_id' => 1]);
        Banco::create(['nome' =>'Cambionet Corretora De Câmbio Ltda.','codigo' => '309','pais_id' => 1]);
        Banco::create(['nome' =>'Vortx Dtvm Ltda','codigo' => '310','pais_id' => 1]);
        Banco::create(['nome' =>'Amazônia Corretora De Câmbio Ltda.','codigo' => '313','pais_id' => 1]);
        Banco::create(['nome' =>'Pi Distribuidora De Títulos E Valores Mobiliários S.A.','codigo' => '315','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Bmg S.A.','codigo' => '318','pais_id' => 1]);
        Banco::create(['nome' =>'Om Distribuidora De Títulos E Valores Mobiliários Ltda','codigo' => '319','pais_id' => 1]);
        Banco::create(['nome' =>'China Construction Bank – Ccb Brasil S.A.','codigo' => '320','pais_id' => 1]);
        Banco::create(['nome' =>'Crefaz Sociedade De Crédito Ao Microempreendedor E A Empresa De Pequeno Porte Lt','codigo' => '321','pais_id' => 1]);
        Banco::create(['nome' =>'Cooperativa De Crédito Rural De Abelardo Luz – Sulcredi/Crediluz','codigo' => '322','pais_id' => 1]);
        Banco::create(['nome' =>'Mercado Pago – Conta Do Mercado Livre','codigo' => '323','pais_id' => 1]);
        Banco::create(['nome' =>'Cartos Sociedade De Crédito Direto S.A.','codigo' => '324','pais_id' => 1]);
        Banco::create(['nome' =>'Órama Distribuidora De Títulos E Valores Mobiliários S.A.','codigo' => '325','pais_id' => 1]);
        Banco::create(['nome' =>'Parati – Crédito, Financiamento E Investimento S.A.','codigo' => '326','pais_id' => 1]);
        Banco::create(['nome' =>'Qi Sociedade De Crédito Direto S.A.','codigo' => '329','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Bari De Investimentos E Financiamentos S.A.','codigo' => '330','pais_id' => 1]);
        Banco::create(['nome' =>'Fram Capital Distribuidora De Títulos E Valores Mobiliários S.A.','codigo' => '331','pais_id' => 1]);
        Banco::create(['nome' =>'Acesso Soluções De Pagamento S.A.','codigo' => '332','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Digio S.A.','codigo' => '335','pais_id' => 1]);
        Banco::create(['nome' =>'Banco C6 S.A – C6 Bank','codigo' => '336','pais_id' => 1]);
        Banco::create(['nome' =>'Super Pagamentos S/A (Superdital)','codigo' => '340','pais_id' => 1]);
        Banco::create(['nome' =>'Itaú Unibanco S.A.','codigo' => '341','pais_id' => 1]);
        Banco::create(['nome' =>'Creditas Sociedade De Crédito Direto S.A.','codigo' => '342','pais_id' => 1]);
        Banco::create(['nome' =>'Ffa Sociedade De Crédito Ao Microempreendedor E À Empresa De Pequeno Porte Ltda.','codigo' => '343','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Xp S/A','codigo' => '348','pais_id' => 1]);
        Banco::create(['nome' =>'Al5 S.A. Crédito, Financiamento E Investimento','codigo' => '349','pais_id' => 1]);
        Banco::create(['nome' =>'Cooperativa De Crédito Rural De Pequenos Agricultores E Da Reforma Agrária Do Ce','codigo' => '350','pais_id' => 1]);
        Banco::create(['nome' =>'Toro Corretora De Títulos E Valores Mobiliários Ltda','codigo' => '352','pais_id' => 1]);
        Banco::create(['nome' =>'Necton Investimentos S.A. Corretora De Valores Mobiliários E Commodities','codigo' => '354','pais_id' => 1]);
        Banco::create(['nome' =>'Ótimo Sociedade De Crédito Direto S.A.','codigo' => '355','pais_id' => 1]);
        Banco::create(['nome' =>'Zema Crédito, Financiamento E Investimento S/A','codigo' => '359','pais_id' => 1]);
        Banco::create(['nome' =>'Trinus Capital Distribuidora De Títulos E Valores Mobiliários S.A.','codigo' => '360','pais_id' => 1]);
        Banco::create(['nome' =>'Cielo S.A.','codigo' => '362','pais_id' => 1]);
        Banco::create(['nome' =>'Socopa Sociedade Corretora Paulista S.A.','codigo' => '363','pais_id' => 1]);
        Banco::create(['nome' =>'Gerencianet S.A.','codigo' => '364','pais_id' => 1]);
        Banco::create(['nome' =>'Solidus S.A. Corretora De Cambio E Valores Mobiliarios','codigo' => '365','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Societe Generale Brasil','codigo' => '366','pais_id' => 1]);
        Banco::create(['nome' =>'Vitreo Distribuidora De Títulos E Valores Mobiliários S.A.','codigo' => '367','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Csf S.A.','codigo' => '368','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Mizuho S.A.','codigo' => '370','pais_id' => 1]);
        Banco::create(['nome' =>'Warren Corretora De Valores Mobiliários E Câmbio Ltda.','codigo' => '371','pais_id' => 1]);
        Banco::create(['nome' =>'Up.P Sociedade De Empréstimo Entre Pessoas S.A.','codigo' => '373','pais_id' => 1]);
        Banco::create(['nome' =>'Realize Crédito, Financiamento E Investimento S.A.','codigo' => '374','pais_id' => 1]);
        Banco::create(['nome' =>'Banco J.P. Morgan S.A.','codigo' => '376','pais_id' => 1]);
        Banco::create(['nome' =>'Ms Sociedade De Crédito Ao Microempreendedor E À Empresa De Pequeno Porte Ltda','codigo' => '377','pais_id' => 1]);
        Banco::create(['nome' =>'Bbc Leasing S.A. – Arrendamento Mercantil','codigo' => '378','pais_id' => 1]);
        Banco::create(['nome' =>'Cooperforte – Cooperativa De Economia E Crédito Mútuo Dos Funcionários De Instit','codigo' => '379','pais_id' => 1]);
        Banco::create(['nome' =>'Picpay Servicos S.A.','codigo' => '380','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Mercedes-Benz Do Brasil S.A.','codigo' => '381','pais_id' => 1]);
        Banco::create(['nome' =>'Fidúcia Sociedade De Crédito Ao Microempreendedor E À Empresa De Pequeno Porte L','codigo' => '382','pais_id' => 1]);
        Banco::create(['nome' =>'Boletobancário.Com Tecnologia De Pagamentos Ltda.','codigo' => '383','pais_id' => 1]);
        Banco::create(['nome' =>'Global Finanças Sociedade De Crédito Ao Microempreendedor E À Empresa De Pequeno','codigo' => '384','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Toyota Do Brasil S.A.','codigo' => '387','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Mercantil Do Brasil S.A.','codigo' => '389','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Gm S.A.','codigo' => '390','pais_id' => 1]);
        Banco::create(['nome' =>'Cooperativa De Crédito Rural De Ibiam – Sulcredi/Ibiam','codigo' => '391','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Volkswagen S.A.','codigo' => '393','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Bradesco Financiamentos S.A.','codigo' => '394','pais_id' => 1]);
        Banco::create(['nome' =>'Hub Pagamentos S.A.','codigo' => '396','pais_id' => 1]);
        Banco::create(['nome' =>'Listo Sociedade De Crédito Direto S.A.','codigo' => '397','pais_id' => 1]);
        Banco::create(['nome' =>'Kirton Bank S.A. – Banco Múltiplo','codigo' => '399','pais_id' => 1]);
        Banco::create(['nome' =>'Cora Sociedade De Crédito Direto S.A.','codigo' => '403','pais_id' => 1]);
        Banco::create(['nome' =>'Sumup Sociedade De Crédito Direto S.A.','codigo' => '404','pais_id' => 1]);
        Banco::create(['nome' =>'Bônuscred Sociedade De Crédito Direto S.A.','codigo' => '408','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Capital S.A.','codigo' => '412','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Safra S.A.','codigo' => '422','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Mufg Brasil S.A.','codigo' => '456','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Sumitomo Mitsui Brasil S.A.','codigo' => '464','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Caixa Geral Brasil S.A.','codigo' => '473','pais_id' => 1]);
        Banco::create(['nome' =>'Citibank N.A.','codigo' => '477','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Itaubank S.A.','codigo' => '479','pais_id' => 1]);
        Banco::create(['nome' =>'Deutsche Bank S.A (Banco Alemão)','codigo' => '487','pais_id' => 1]);
        Banco::create(['nome' =>'Jpmorgan Chase Bank','codigo' => '488','pais_id' => 1]);
        Banco::create(['nome' =>'Ing Bank N.V.','codigo' => '492','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Rep Oriental Uruguay','codigo' => '494','pais_id' => 1]);
        Banco::create(['nome' =>'La Provincia Buenos Aires Banco','codigo' => '495','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Credit Suisse (Brl) S.A.','codigo' => '505','pais_id' => 1]);
        Banco::create(['nome' =>'Senso Ccvm S.A.','codigo' => '545','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Luso Brasileiro S.A.','codigo' => '600','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Industrial Do Brasil S.A.','codigo' => '604','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Vr S.A.','codigo' => '610','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Paulista','codigo' => '611','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Guanabara S.A.','codigo' => '612','pais_id' => 1]);
        Banco::create(['nome' =>'Omni Banco S.A.','codigo' => '613','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Pan S.A.','codigo' => '623','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Ficsa S.A.','codigo' => '626','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Smartbank S.A.','codigo' => '630','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Rendimento S.A.','codigo' => '633','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Triangulo S.A (Banco Triângulo)','codigo' => '634','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Sofisa S.A (Sofisa Direto)','codigo' => '637','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Alvorada S.A.','codigo' => '641','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Pine S.A.','codigo' => '643','pais_id' => 1]);
        Banco::create(['nome' =>'Itaú Unibanco Holding Bm S.A.','codigo' => '652','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Indusval S.A.','codigo' => '653','pais_id' => 1]);
        Banco::create(['nome' =>'Banco A.J. Renner S.A.','codigo' => '654','pais_id' => 1]);
        Banco::create(['nome' =>'Neon Pagamentos S.A (Memso Código Do Banco Votorantim)','codigo' => '655','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Daycoval S.A.','codigo' => '707','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Ourinvest S.A.','codigo' => '712','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Cetelem S.A.','codigo' => '739','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Ribeirão Preto S.A.','codigo' => '741','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Semear S.A.','codigo' => '743','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Citibank S.A.','codigo' => '745','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Modal S.A.','codigo' => '746','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Rabobank Internacional Do Brasil S.A.','codigo' => '747','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Cooperativa Sicredi S.A.','codigo' => '748','pais_id' => 1]);
        Banco::create(['nome' =>'Scotiabank Brasil','codigo' => '751','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Bnp Paribas Brasil S.A.','codigo' => '752','pais_id' => 1]);
        Banco::create(['nome' =>'Novo Banco Continental S.A Bm','codigo' => '753','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Sistema S.A.','codigo' => '754','pais_id' => 1]);
        Banco::create(['nome' =>'Bank Of America Merrill Lynch Banco Múltiplo S.A.','codigo' => '755','pais_id' => 1]);
        Banco::create(['nome' =>'Bancoob – Banco Cooperativo Do Brasil S.A.','codigo' => '756','pais_id' => 1]);
        Banco::create(['nome' =>'Banco Keb Hana Do Brasil S.A.','codigo' => '757','pais_id' => 1]);
        Banco::create(['nome' =>'Next Bank (Mesmo Código Do Bradesco)','codigo' => '237','pais_id' => 1]);
    }
}
