<?php

namespace Database\Seeders;

use App\Models\Endereco\Pais;
use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Pais::create(['nome' => 'Brasil', 'nacionalidade' => 'brasileiro', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Afeganistão', 'nacionalidade' => 'afegã', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'África do Sul', 'nacionalidade' => 'sul-africana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Albânia', 'nacionalidade' => 'albanesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Alemanha', 'nacionalidade' => 'alemã', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Andorra', 'nacionalidade' => 'andorrana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Angola', 'nacionalidade' => 'angolana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Antígua e Barbuda', 'nacionalidade' => 'antiguana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Arábia Saudita ', 'nacionalidade' => 'saudita', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Argélia', 'nacionalidade' => 'argelina', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Argentina', 'nacionalidade' => 'argentino', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Armênia', 'nacionalidade' => 'armênia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Austrália', 'nacionalidade' => 'australiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Áustria', 'nacionalidade' => 'austríaca', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Azerbaidjão', 'nacionalidade' => 'azerbaijana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Bahamas', 'nacionalidade' => 'Bahamense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Bangladesh', 'nacionalidade' => 'bengalesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Barbados', 'nacionalidade' => 'barbadiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Belarus', 'nacionalidade' => 'bielo-russa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Bélgica', 'nacionalidade' => 'Belga', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Belize', 'nacionalidade' => 'belizenha', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Benin', 'nacionalidade' => 'Beninense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Bolívia', 'nacionalidade' => 'boliviana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Bósnia-Herzegóvina', 'nacionalidade' => 'bósnia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Botsuana', 'nacionalidade' => 'bechuana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Brasil', 'nacionalidade' => 'brasileira', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Brunei', 'nacionalidade' => 'bruneana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Bulgária', 'nacionalidade' => 'búlgara', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Burkina', 'nacionalidade' => 'Burquinense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Burundi', 'nacionalidade' => 'burundinesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Butão', 'nacionalidade' => 'butanesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Cabo Verde ', 'nacionalidade' => 'caboverdiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Camarões', 'nacionalidade' => 'camaronesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Camboja', 'nacionalidade' => 'cambojana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Canadá', 'nacionalidade' => 'Canadense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Catar', 'nacionalidade' => 'catariana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Cazaquistão', 'nacionalidade' => 'Cazaque', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Chade', 'nacionalidade' => 'chadiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Chile', 'nacionalidade' => 'chilena', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'China', 'nacionalidade' => 'chinesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Chipre', 'nacionalidade' => 'Cipriota', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Cingapura', 'nacionalidade' => 'cingapuriana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Colômbia', 'nacionalidade' => 'colombiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Comores', 'nacionalidade' => 'Comorense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Congo', 'nacionalidade' => 'congolesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Coréia do Norte', 'nacionalidade' => 'norte-coreana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Coréia do Sul', 'nacionalidade' => 'sul-coreana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Costa', 'nacionalidade' => 'Marfinense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Costa Rica ', 'nacionalidade' => 'costarriquenha', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Croácia', 'nacionalidade' => 'Croata', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Cuba', 'nacionalidade' => 'cubana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Dinamarca', 'nacionalidade' => 'dinamarquesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Djibuti', 'nacionalidade' => 'djibutiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Dominica', 'nacionalidade' => 'dominicana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Egito', 'nacionalidade' => 'egípcia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'El Salvador ', 'nacionalidade' => 'salvadorenha', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Emirados', 'nacionalidade' => 'Emirense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Equador', 'nacionalidade' => 'equatoriana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Eritreia', 'nacionalidade' => 'eritreia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Eslováquia', 'nacionalidade' => 'eslovaca', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Eslovênia', 'nacionalidade' => 'eslovena', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Espanha', 'nacionalidade' => 'espanhola', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Estados Unidos', 'nacionalidade' => 'americana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Estônia', 'nacionalidade' => 'estoniana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Etiópia', 'nacionalidade' => 'Etíope', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Federação Russa', 'nacionalidade' => 'russa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Fiji', 'nacionalidade' => 'fijiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Filipinas', 'nacionalidade' => 'filipina', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Finlândia', 'nacionalidade' => 'finlandesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'França', 'nacionalidade' => 'francesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Gabão', 'nacionalidade' => 'gabonesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Gâmbia', 'nacionalidade' => 'gambiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Gana', 'nacionalidade' => 'ganesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Geórgia', 'nacionalidade' => 'georgiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Granada', 'nacionalidade' => 'granadina', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Grécia', 'nacionalidade' => 'grega', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Guatemala', 'nacionalidade' => 'guatemalteca', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Guiana', 'nacionalidade' => 'guianesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Guiné-Bissau', 'nacionalidade' => 'Guineense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Guiné-Equatorial', 'nacionalidade' => 'guinéu-equatoriana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Haiti', 'nacionalidade' => 'haitiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Holanda', 'nacionalidade' => 'holandesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Honduras', 'nacionalidade' => 'hondurenha', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Hungria', 'nacionalidade' => 'húngara', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Iémen', 'nacionalidade' => 'Iemenita', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Ilhas Marshall', 'nacionalidade' => 'marshalina', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Ilhas Salomão', 'nacionalidade' => 'salomônica', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Índia', 'nacionalidade' => 'indiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Indonésia', 'nacionalidade' => 'indonésia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Irã', 'nacionalidade' => 'iraniana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Iraque', 'nacionalidade' => 'iraquiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Irlanda', 'nacionalidade' => 'irlandesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Islândia', 'nacionalidade' => 'islandesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Israel', 'nacionalidade' => 'Israelense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Itália', 'nacionalidade' => 'italiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Jamaica', 'nacionalidade' => 'jamaicana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Japão', 'nacionalidade' => 'japonesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Jordânia', 'nacionalidade' => 'jordaniana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Kiribati', 'nacionalidade' => 'kiribatiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Kuwait', 'nacionalidade' => 'kuwaitiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Laos', 'nacionalidade' => 'laosiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Lesoto', 'nacionalidade' => 'lesota', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Letônia', 'nacionalidade' => 'letã', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Líbano', 'nacionalidade' => 'libanesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Libéria', 'nacionalidade' => 'liberiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Líbia', 'nacionalidade' => 'líbia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Liechtenstein', 'nacionalidade' => 'Liechtensteiniense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Lituânia', 'nacionalidade' => 'lituana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Luxemburgo', 'nacionalidade' => 'luxemburguesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Macedônia', 'nacionalidade' => 'macedônia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Madagascar', 'nacionalidade' => 'Malgache', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Malásia', 'nacionalidade' => 'malaia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Malauí', 'nacionalidade' => 'malauiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Maldivas', 'nacionalidade' => 'maldiva', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Mali', 'nacionalidade' => 'malinesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Malta', 'nacionalidade' => 'maltesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Marrocos', 'nacionalidade' => 'marroquina', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Maurício', 'nacionalidade' => 'mauriciana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Mauritânia', 'nacionalidade' => 'mauritana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'México', 'nacionalidade' => 'mexicana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Mianmar', 'nacionalidade' => 'birmanesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Micronésia', 'nacionalidade' => 'micronésia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Moçambique', 'nacionalidade' => 'moçambicana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Moldávia', 'nacionalidade' => 'moldávia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Mônaco', 'nacionalidade' => 'monegasca', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Mongólia', 'nacionalidade' => 'Mongol', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Montenegro', 'nacionalidade' => 'montenegrina', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Namíbia', 'nacionalidade' => 'namibiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Nauru', 'nacionalidade' => 'nauruana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Nepal', 'nacionalidade' => 'nepalesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Nicarágua', 'nacionalidade' => 'Nicaraguense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Níger', 'nacionalidade' => 'nigerina', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Nigéria', 'nacionalidade' => 'nigeriana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Noruega', 'nacionalidade' => 'norueguesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Nova Zelândia', 'nacionalidade' => 'neozelandesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Omã', 'nacionalidade' => 'Omani', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Palau', 'nacionalidade' => 'Palauense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Panamá', 'nacionalidade' => 'panamenha', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Papua Nova Guiné', 'nacionalidade' => 'papuásia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Paquistão', 'nacionalidade' => 'paquistanesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Paraguai', 'nacionalidade' => 'paraguaia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Peru', 'nacionalidade' => 'peruana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Polônia', 'nacionalidade' => 'polonesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Portugal', 'nacionalidade' => 'portuguesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Quênia', 'nacionalidade' => 'queniana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Reino Unido', 'nacionalidade' => 'inglesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'República Centro-Africana', 'nacionalidade' => 'centro-africana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'República Dominicana', 'nacionalidade' => 'dominicana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'República Tcheca', 'nacionalidade' => 'tcheca', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Romênia', 'nacionalidade' => 'romena', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Ruanda', 'nacionalidade' => 'ruandesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Samoa', 'nacionalidade' => 'samoana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'San e Marino', 'nacionalidade' => 'samarinesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Santa', 'nacionalidade' => 'Santa-lucense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'São', 'nacionalidade' => 'São-cristovense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'São', 'nacionalidade' => 'Santomense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'São Vicente Granadinas', 'nacionalidade' => 'são-vicentina', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Seicheles', 'nacionalidade' => 'Seichelense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Senegal', 'nacionalidade' => 'senegalesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Serra Leoa', 'nacionalidade' => 'leonesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Sérvia', 'nacionalidade' => 'sérvia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Síria', 'nacionalidade' => 'síria', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Somália', 'nacionalidade' => 'Somali', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Sri Lanka', 'nacionalidade' => 'cingalesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Suazilândia', 'nacionalidade' => 'suazi', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Sudão', 'nacionalidade' => 'sudanesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Suécia', 'nacionalidade' => 'suéca', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Suíça', 'nacionalidade' => 'suíça', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Suriname', 'nacionalidade' => 'surinamesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Tailândia', 'nacionalidade' => 'tailandesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Tajiquistão', 'nacionalidade' => 'Tajique', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Tanzânia', 'nacionalidade' => 'tanzaniana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Timor', 'nacionalidade' => 'Timorense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Togo', 'nacionalidade' => 'togonesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Tonga', 'nacionalidade' => 'tongalesa', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Trinidad e Tobago', 'nacionalidade' => 'trinitina', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Tunísia', 'nacionalidade' => 'tunisiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Turcomenistão', 'nacionalidade' => 'turcomana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Turquia', 'nacionalidade' => 'turca', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Tuvalu', 'nacionalidade' => 'tuvaluana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Ucrânia', 'nacionalidade' => 'ucraniana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Uganda', 'nacionalidade' => 'Ugandense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Uruguai', 'nacionalidade' => 'uruguaia', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Usbequistão', 'nacionalidade' => 'Uzbeque', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Vanuatu', 'nacionalidade' => 'Vanuatense', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Venezuela', 'nacionalidade' => 'venezuelana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Vietnã', 'nacionalidade' => 'Vietnamita', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Zâmbia', 'nacionalidade' => 'zambiana', 'codigo_de_area' => '55']);
        Pais::create(['nome' => 'Zimbábue', 'nacionalidade' => 'zimbabuana', 'codigo_de_area' => '55']);
    }
}
