version: '3'
services:
  app:
    build: .
    container_name: app_bleauboard
    volumes:
      - '.:/var/www'
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build: .docker/nginx
    container_name: nginx_bleauboard
    restart: always
    tty: true
    ports:
      - '8000:80'
    volumes:
      - '.:/var/www'
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db_bleauboard
    networks: 
      - app-network
    ports:
    - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=bleauboard
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=bleau
      - MYSQL_PASSWORD=secret

networks:
  app-network:
    driver: bridge
